### ISSUE TITLE
ssh loopback

### ISSUE THREAD

**Issue by khojir** [MichaelBosello/carla-colab#1]
I have tried to use loopback to map port 2000 of my system to port 2000 of the remote server.
I use something like this:
```
ssh -o UserKnownHostsFile=/dev/null -o VisualHostKey=yes -L 2000:localhost:2000 -p [my-port] colab@[my-address].ngrok.io
```
When I run this command, I can see that port 2000 in my system is open.
```
tcp        0      0 127.0.0.1:2000          0.0.0.0:*               LISTEN      22020/ssh           
tcp6       0      0 ::1:2000                :::*                    LISTEN      22020/ssh
```
But when I run the manual_control.py, I will get this error:
```
RuntimeError: time-out of 20000ms while waiting for the simulator, make sure the simulator is ready and connected to 127.0.0.1:2000
```
While I can run this script on my server.

I'm not sure, but maybe it's because of version mismatch:
```
WARNING: Client API version     = 0.9.7-12-g1f7669e 
WARNING: Simulator API version  = 0.9.8 
```

**Comment by MichaelBosello** [comment]
This tutorial is designed to run both client and server on Colab.

Anyway, I would suggest to try ping the Colab remote desktop to check out if the connection works and if you can reach it in less than 20 seconds.

For the mismatching version, you can change the download link to use the one you want.

**Comment by MichaelBosello** [comment]
I have tested port forwarding and it works ([added to the tutorial](https://github.com/MichaelBosello/carla-colab/commit/d339b7a8d74e76a68d03ce31e1b29cfca5117ccc)).

Try to run manual_control.py two times as it could have delays in opening the connection, resulting in a timeout.
