### ISSUE TITLE
Colab always getting disconnected after sometime

### ISSUE THREAD

**Issue by Andre1998Shuvam** [MichaelBosello/carla-colab#13]
Hi! When I try to run this, Google Colab automatically gets disconnected every time. How can I solve this issue?

**Comment by Andre1998Shuvam** [comment]
Hi! Kindly let me know how I can solve this issue at your earliest convenience.

**Comment by Andre1998Shuvam** [comment]
Please reply soon

**Comment by Andre1998Shuvam** [comment]
??

**Comment by MichaelBosello** [comment]
Google Colab doesn't allow the remote desktop or ssh connection to their instances anymore, see [colaboratory faq](https://research.google.com/colaboratory/faq.html). I will archive this repository as it is not usable anymore.
