### ISSUE TITLE
ERROR: (localhost:2000) failed to read data: timed out

### ISSUE THREAD

**Issue by FelipeCrispim** [MichaelBosello/carla-colab#3]
Hello,

When I try to run both server and client, I get few errors:

- In client side is "ERROR: (localhost:2000) failed to read data: timed out".
- In server side is "ERROR: tcpserver 0 : error reading message: Operation canceled" and "ERROR: tcpserver 2000 : error reading message: End of file".

I have tried to change the port, but I got the same error. Have you ever faced this problem or you know how to solve it? 

Thanks in advance.

**Comment by MichaelBosello** [comment]
Are you executing them on the Colab remote desktop?

If you follow the tutorial until "Run Carla", does the snippet `! sudo -u colab DISPLAY=:1 vglrun /home/colab/carla/CarlaUE4.sh` show any error? If not, you should see the Carla server running on the VNC desktop.

By opening a terminal in the VNC desktop, you can run a test client with:
```
pip install pygame
cd /home/colab/carla/PythonAPI/examples
python manual_control.py
```
