### ISSUE TITLE
CARLA opens only the map; no car is rendered

### ISSUE THREAD

**Issue by nagasanjay** [MichaelBosello/carla-colab#4]
When I run carla, only the map ( The small window at the bottom right of the image you displayed in readme ) only opens. The main window with the car isn't rendered.
![carla colab](https://user-images.githubusercontent.com/43279026/90472283-c30ec080-e13d-11ea-9cbb-719e0fad4180.png)

**Comment by MichaelBosello** [comment]
You have started only the Carla server.
To start a client (that controls a car), you need to follow this part of the tutorial:

### Client control with python
You can run CARLA clients from the remote desktop
From a terminal on the remote desktop

#### Install requirement

1.  `sudo pip install pygame`

> - The password for colab user is shown above

#### Run the 'manual control' example
2. `cd /home/colab/carla/PythonAPI/examples`
3. `python manual_control.py`
