### ISSUE TITLE
Connect to carla server from a client in my local machine

### ISSUE THREAD

**Issue by nagasanjay** [MichaelBosello/carla-colab#5]
Is there any possible way to connect the client in my local machine to the CARLA server running on colab ?

**Comment by MichaelBosello** [comment]
As Carla is network based, it should be possible to use remote port forwarding to connect a local client to a remote server. Check out: 
https://github.com/carla-simulator/carla/issues/775 
https://github.com/carla-simulator/carla/issues/624

If you were successful and you could write the steps to use a local client, I would add it to the tutorial.

**Comment by MichaelBosello** [comment]
I have added to the tutorial the steps necessary to connect a client in your local machine to the remote server ([commit 1](https://github.com/MichaelBosello/carla-colab/commit/3be1bb1b6b4a31a3c6169728fca63bf5d4b9745d), [commit 2](https://github.com/MichaelBosello/carla-colab/commit/d339b7a8d74e76a68d03ce31e1b29cfca5117ccc))
