### ISSUE TITLE
kex_exchange_identification: Connection closed by remote host

### ISSUE THREAD

**Issue by Saikiran0121** [MichaelBosello/carla-colab#8]
when i run colab link ,it is giving the  error "kex_exchange_identification: Connection closed by remote host""
I dont know anything about it.

**Comment by MichaelBosello** [comment]
It seems Google has blocked Ngrok (see [this issue](https://github.com/demotomohiro/remocolab/issues/79)). You should use Argo Tunnel instead (see the [readme of remocolab](https://github.com/demotomohiro/remocolab/blob/master/README.md)). I will update the code/tutorial in the future. If you will update the tutorial yourself, do feel free to send a pull request.

**Comment by MichaelBosello** [comment]
Tutorial updated to use Argo tunnel instead of Ngrok (commit [here](https://github.com/MichaelBosello/carla-colab/commit/d131625615c9701db6c111ecedc855102819f6e5)).
