### ISSUE TITLE
Colab GPU limits exceeded

### ISSUE THREAD

**Issue by PalaashAgrawal** [MichaelBosello/carla-colab#9]
I can't run this notebook in colab. As soon as I try downloading CARLA ("! sudo -u colab wget -O /home/colab/CARLA.tar.gz https://carla-releases.s3.eu-west-3.amazonaws.com/Linux/CARLA_0.9.10.tar.gz"), Colab stops by saying that COlab GPU limits have exceeded. I haven't used Colab in a few days, so its not because I've been running the GPU for a long time. Is it possible that Colab bans me because of downloading a lot of files very fast?

**Comment by MichaelBosello** [comment]
No, Colab users are not banned for downloading files. The error is actually the one reported i.e., GPU limits exceeded.
It is a coincidence that it stops during the download (you can try run other code if you want)

I have personal experience on this: Colab keeps shutting down my instances even with the pro subscription as I used Colab too much in a short time, apparently (BTW, I didn't use Carla at the time as it was a different project). Even after several months, I cannot use Colab with my primary account. I found confirmation in [this Reddit](https://www.reddit.com/r/GoogleColab/comments/lgz04a/regarding_usage_limits_in_colab_some_common_sense/).

**Comment by PalaashAgrawal** [comment]
Oh wow, this is a surprise. Thanks a lot for your help. I'll probably have
to shift to some other platform.
